import "../scss/search-form.scss";
import "../scss/main.scss";
import "./page.scss";
import "../scss/header.scss";
import "./film-data";
import "./film-data-1";
import "slick-carousel/slick/slick.scss";
import "slick-carousel/slick/slick-theme.scss";
import "../scss/headerAbout.scss";
